services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: no
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
